#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "James Thurley"
email = "james@thurley.com"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
