#!/bin/bash

echo "Creating symlinks for dotfiles to $HOME"


# Define the source directory containing the dotfiles
SOURCE_DIR="$PWD/dotfiles"
# Define the target directory where the symbolic links will be created
TARGET_DIR="$HOME"

# Use find to recursively search for dotfiles in the source directory
# Dotfiles are assumed to be any files or directories starting with a dot ('.')
find "$SOURCE_DIR" -name "*" -type f -print0 | while IFS= read -r -d '' file; do
    # Skip the source directory itself
    if [ "$file" == "$SOURCE_DIR" ]; then
        continue
    fi

    # Compute the relative path of the file/directory
    relative_path="${file#$SOURCE_DIR/}"
    # Determine the target path in the user's home directory
    target="$TARGET_DIR/$relative_path"


    echo "Processing $file"

    # Create the target directory structure if it does not exist
    if ! mkdir -p "$(dirname "$target")"; then
        echo "Failed to create directory for $(dirname "$target")"
        continue
    else
        echo "Created directory for $(dirname "$target")"
    fi

    # Create a symbolic link at the target location pointing to the source file
    if ln -snf "$file" "$target"; then
        echo "Linked $file to $target"
    else
        echo "Failed to link $file to $target"
    fi
done


# Source .zshrc to update env
# Ignore the errors generated by this source.
# They only appear during this process. They work properly on new shell startup.
echo "Linked dotfiles. Please restart your shell."
