#!/bin/bash

echo "Creating symlinks for dotfiles to $HOME"

for f in dotfiles/\.[^.]*; do
FILE="$(basename $f)"
ln -sf "$PWD/dotfiles/$FILE" "$HOME"
done

# Source .zshrc to update env
# Ignore the errors generated by this source.
# They only appear during this process. They work properly on new shell startup.
echo "Linked dotfiles. Please restart your shell."